### PR TITLE
Fix gcc 4.8 5 compilation errors for IOSS used in VTK

### PR DESCRIPTION
**Pull request by spyridon97**
The purpose of this PR is to fix compilations issues using gcc 4.8.5 for the IOSS package which is utilized in VTK

@mathstuf

### CODE REVIEW

**Review by gsjaardema — COMMENTED** [review]
Sorry, I'm not going to revert back to pre C99...

**Review by gsjaardema — COMMENTED** [review]
Those look good. Thanks.

**Comment by spyridon97** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by spyridon97** [comment]
recheck

**Comment by spyridon97** [comment]
recheck

**Comment by spyridon97** [comment]
@gsjaardema CI has passed. CI does not understand that i have read and agreed to the CLA document.

**Comment by spyridon97** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by spyridon97** [comment]
recheck

**Comment by gsjaardema** [comment]
@spyridon97 Not sure why.  I reran it manually and it worked...

**Comment by gsjaardema** [comment]
I could move Ioss_Getline.c to be a C++ file which would possibly solve the issue you are seing without reverting to pre-C99 if that works for you?

**Comment by spyridon97** [comment]
> I could move Ioss_Getline.c to be a C++ file which would possibly solve the issue you are seing without reverting to pre-C99 if that works for you?
That should work for me.

**Comment by gsjaardema** [comment]
I think the `c_sources` is on your side.  I don't see it in my code.

**Comment by gsjaardema** [comment]
I don't think I can remove that commit from the PR.  I have moved Ioss_Getline.c to a C++ file.  I can also just make the ParallelUtils changes outside this PR which might be the easiest way to do this...

**Comment by spyridon97** [comment]
>  I can also just make the ParallelUtils changes outside this PR which might be the easiest way to do this...

That sounds good!

**Comment by gsjaardema** [comment]
Commit [926571d](https://github.com/sandialabs/seacas/pull/353/commits/926571d567aff115a8a9a14027d1c2ed1109c12a) has been comitted outside this PR.  The other commit in the PR is not needed due to changing Ioss_Getline.c to be a C++ file.

**Pull request closed without merging**
