### PR TITLE
Ioss zero copy

### PR DESCRIPTION
**Pull request by gsjaardema**
Prototype implementation to support the zero-copy API discussed in #282 

@tjotaha @mathstuf @utkarshayachit

### CODE REVIEW

**Comment by mathstuf** [comment]
@spyridon97

**Comment by spyridon97** [comment]
Ι am not an IOSS expert, but the changes seem good to me.

The only thing that i would change is to convert the return type of get_field_data to an enum that inherits int64_t (to maintain backwards - compatibility) with specific enum values that are easily interpretable.

**Comment by utkarshayachit** [comment]
+1

**Comment by gsjaardema** [comment]
> An IOSS database that supports zero_copy reads needs to provide an implementation of this new method in Ioss::GroupingEntity?
> 
> ```c++
> int64_t Ioss::GroupingEntity::internal_get_field_data(const Ioss::Field &field, void ** /*data*/,
>                                                       size_t * /*data_size*/) const
> ```
Yes.

> 
> Then the code that reads from this IOSS database needs to specify all of the Ioss::Field() objects being added to an Ioss::GroupingEntity as being zero_copy (code below from ParaView's IOSS reader)?
> 
> ```c++
>         block->field_add(
>           Ioss::Field(std::get<0>(field), std::get<1>(field), "scalar", role, elementCount));
> ```
Yes, the DatabaseIO object that is going to support zero-copy reads would specify which fields that it is adding would be zero_copy_enabled.  A client of that database could access the field data either way -- provide a memory space for the data to be stored in, or ask for the pointer to the memory space managed by the DatabaseIO object.
> 
> Should the Ioss::Field constructor contain a parameter to set zero_copy to true?
Possibly.  I had thought about that but didn't decide either way.  I will take a look at the Ioss::Field constructor(s) and see how cleanly that could be done.  An optional parameter would make it easy, or another constructor...

**Comment by gsjaardema** [comment]
@tjotaha 

> Should the Ioss::Field constructor contain a parameter to set zero_copy to true?

How about something like this:
```
        block->field_add(
          Ioss::Field(std::get<0>(field), std::get<1>(field), "scalar", role, elementCount).set_zero_copyable());
```
Looking at the current constructors, there are already some optional parameters, so adding yet another possibility of being able to pass a TRUE/FALSE parameter or enum value for setting zero copy status might get really confusing.  

With the above idiom, it should give almost the same brevity, but not the confusion or possible parse issues...

**Comment by tjotaha** [comment]
Do we need a Boolean method on IODatabase to indicate that the database supports zero-copy?

**Pull request merged**
